name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub (if you need to push the image)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and optionally push the Docker image
      - name: Build Docker image
        uses: docker/setup-buildx-action
        with:
          context: .
          file: ./banking-control-panel/Dockerfile
          push: false # Set to false if you don't want to push the image
          tags: your-image-name:latest
